'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_permisos
    Public Property id_permisos As Integer
    Public Property per_nombre As String
    Public Property per_correlativo As String
    Public Property per_estado As Boolean

    Public Overridable Property tbl_mf_detalle_usuarios As ICollection(Of tbl_mf_detalle_usuarios) = New HashSet(Of tbl_mf_detalle_usuarios)

End Class
