'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_mf_detalle_usuarios
    Public Property id_detalle As Integer
    Public Property id_permisos As Integer
    Public Property id_modulo As Integer
    Public Property id_usuarios As Integer

    Public Overridable Property tbl_mf_modulo As tbl_mf_modulo
    Public Overridable Property tbl_mf_permisos As tbl_mf_permisos
    Public Overridable Property tbl_mf_usuarios As tbl_mf_usuarios

End Class
