'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB2Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB2Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property tbl_mf_detalle_usuarios() As DbSet(Of tbl_mf_detalle_usuarios)
    Public Property tbl_mf_modulo() As DbSet(Of tbl_mf_modulo)
    Public Property tbl_mf_permisos() As DbSet(Of tbl_mf_permisos)
    Public Property tbl_mf_usuarios() As DbSet(Of tbl_mf_usuarios)

End Class
